
INSERT INTO public.icd10_codes (code, description, category, block, chapter, is_billable, common_india) VALUES
('A01.0','Typhoid fever','Infectious Diseases','A00-A09','I',true,true),
('A01.1','Paratyphoid fever A','Infectious Diseases','A00-A09','I',true,true),
('A01.4','Paratyphoid fever, unspecified','Infectious Diseases','A00-A09','I',true,true),
('A00.9','Cholera, unspecified','Infectious Diseases','A00-A09','I',true,true),
('A02.0','Salmonella enteritis','Infectious Diseases','A00-A09','I',true,true),
('A06.0','Acute amoebic dysentery','Infectious Diseases','A00-A09','I',true,true),
('A06.9','Amoebiasis, unspecified','Infectious Diseases','A00-A09','I',true,true),
('A09.9','Gastroenteritis & colitis, unspecified','Infectious Diseases','A00-A09','I',true,true),
('A15.0','Pulmonary tuberculosis, sputum-positive','Infectious Diseases','A15-A19','I',true,true),
('A15.3','Pulmonary tuberculosis, bacteriologically unspecified','Infectious Diseases','A15-A19','I',true,true),
('A15.9','Pulmonary tuberculosis, unspecified','Infectious Diseases','A15-A19','I',true,true),
('A16.2','Pulmonary tuberculosis without mention of bacteriology','Infectious Diseases','A15-A19','I',true,true),
('A17.0','Tuberculous meningitis','Infectious Diseases','A15-A19','I',true,true),
('A18.0','Tuberculosis of bones and joints','Infectious Diseases','A15-A19','I',true,true),
('A18.1','Tuberculosis of genitourinary system','Infectious Diseases','A15-A19','I',true,true),
('A18.3','Tuberculosis of intestines, peritoneum','Infectious Diseases','A15-A19','I',true,true),
('A19.9','Miliary tuberculosis, unspecified','Infectious Diseases','A15-A19','I',true,true),
('B50.9','Plasmodium falciparum malaria, unspecified','Infectious Diseases','B50-B64','I',true,true),
('B51.9','Plasmodium vivax malaria, unspecified','Infectious Diseases','B50-B64','I',true,true),
('B54','Unspecified malaria','Infectious Diseases','B50-B64','I',true,true),
('A90','Dengue fever (classical)','Infectious Diseases','A80-A89','I',true,true),
('A91','Dengue haemorrhagic fever','Infectious Diseases','A80-A89','I',true,true),
('A92.0','Chikungunya virus disease','Infectious Diseases','A80-A89','I',true,true),
('B15.0','Hepatitis A with hepatic coma','Infectious Diseases','B15-B19','I',true,true),
('B15.9','Hepatitis A without hepatic coma','Infectious Diseases','B15-B19','I',true,true),
('B16.2','Acute hepatitis B without delta-agent, with coma','Infectious Diseases','B15-B19','I',true,true),
('B16.9','Acute hepatitis B without delta-agent, without coma','Infectious Diseases','B15-B19','I',true,true),
('B17.1','Acute hepatitis C','Infectious Diseases','B15-B19','I',true,true),
('B18.1','Chronic viral hepatitis B','Infectious Diseases','B15-B19','I',true,true),
('B18.2','Chronic viral hepatitis C','Infectious Diseases','B15-B19','I',true,true),
('B19.9','Unspecified viral hepatitis','Infectious Diseases','B15-B19','I',true,true),
('B20.0','HIV disease resulting in mycobacterial infection','Infectious Diseases','B20-B24','I',true,true),
('B24','Unspecified HIV disease','Infectious Diseases','B20-B24','I',true,true),
('Z21','Asymptomatic HIV infection status','Infectious Diseases','B20-B24','I',true,true),
('A40.9','Streptococcal septicaemia, unspecified','Infectious Diseases','A38-A41','I',true,true),
('A41.0','Septicaemia due to Staphylococcus aureus','Infectious Diseases','A38-A41','I',true,true),
('A41.5','Septicaemia due to other Gram-negative organisms','Infectious Diseases','A38-A41','I',true,true),
('A41.9','Septicaemia, unspecified','Infectious Diseases','A38-A41','I',true,true),
('N39.0','Urinary tract infection, unspecified','Genitourinary','N30-N39','XIV',true,true),
('A37.0','Whooping cough due to B.pertussis','Infectious Diseases','A35-A37','I',true,true),
('A38','Scarlet fever','Infectious Diseases','A30-A49','I',true,true),
('A46','Erysipelas','Infectious Diseases','A30-A49','I',true,true),
('B05.9','Measles without complication','Infectious Diseases','B00-B09','I',true,true),
('B01.9','Varicella without complication','Infectious Diseases','B00-B09','I',true,true),
('B02.9','Zoster without complication','Infectious Diseases','B00-B09','I',true,true),
('B34.9','Viral infection, unspecified','Infectious Diseases','B25-B34','I',true,true),
('C18.9','Malignant neoplasm of colon, unspecified','Neoplasms','C15-C26','II',true,true),
('C20','Malignant neoplasm of rectum','Neoplasms','C15-C26','II',true,true),
('C22.0','Liver cell carcinoma','Neoplasms','C15-C26','II',true,true),
('C25.9','Malignant neoplasm of pancreas, unspecified','Neoplasms','C15-C26','II',true,true),
('C34.9','Malignant neoplasm of bronchus/lung, unspecified','Neoplasms','C30-C39','II',true,true),
('C50.9','Malignant neoplasm of breast, unspecified','Neoplasms','C50','II',true,true),
('C53.9','Malignant neoplasm of cervix uteri, unspecified','Neoplasms','C51-C58','II',true,true),
('C54.1','Malignant neoplasm of endometrium','Neoplasms','C51-C58','II',true,true),
('C61','Malignant neoplasm of prostate','Neoplasms','C60-C63','II',true,true),
('C67.9','Malignant neoplasm of bladder, unspecified','Neoplasms','C64-C68','II',true,true),
('C71.9','Malignant neoplasm of brain, unspecified','Neoplasms','C69-C72','II',true,true),
('C73','Malignant neoplasm of thyroid gland','Neoplasms','C73-C75','II',true,true),
('C80.9','Malignant neoplasm, unspecified','Neoplasms','C76-C80','II',true,true),
('C91.0','Acute lymphoblastic leukaemia','Neoplasms','C90-C96','II',true,true),
('C92.0','Acute myeloid leukaemia','Neoplasms','C90-C96','II',true,true),
('D50.9','Iron deficiency anaemia, unspecified','Blood','D50-D53','III',true,true),
('D51.9','Vitamin B12 deficiency anaemia, unspecified','Blood','D50-D53','III',true,true),
('D52.9','Folate deficiency anaemia, unspecified','Blood','D50-D53','III',true,true),
('D55.0','Anaemia due to G6PD deficiency','Blood','D55-D59','III',true,true),
('D56.1','Beta thalassaemia','Blood','D55-D59','III',true,true),
('D57.1','Sickle-cell disease without crisis','Blood','D55-D59','III',true,true),
('D64.9','Anaemia, unspecified','Blood','D60-D64','III',true,true),
('D65','Disseminated intravascular coagulation','Blood','D65-D69','III',true,true),
('D69.3','Idiopathic thrombocytopenic purpura','Blood','D65-D69','III',true,true),
('E10.9','Type 1 diabetes mellitus without complications','Endocrine','E10-E14','IV',true,true),
('E11.0','Type 2 diabetes with coma','Endocrine','E10-E14','IV',true,true),
('E11.6','Type 2 diabetes with other specified complications','Endocrine','E10-E14','IV',true,true),
('E11.7','Type 2 diabetes with multiple complications','Endocrine','E10-E14','IV',true,true),
('E11.9','Type 2 diabetes mellitus without complications','Endocrine','E10-E14','IV',true,true),
('E13.9','Other specified diabetes mellitus, without complication','Endocrine','E10-E14','IV',true,true),
('E14.9','Unspecified diabetes mellitus, without complications','Endocrine','E10-E14','IV',true,true),
('E03.9','Hypothyroidism, unspecified','Endocrine','E00-E07','IV',true,true),
('E05.0','Thyrotoxicosis with diffuse goitre','Endocrine','E00-E07','IV',true,true),
('E05.9','Thyrotoxicosis, unspecified','Endocrine','E00-E07','IV',true,true),
('E40','Kwashiorkor','Endocrine','E40-E46','IV',true,true),
('E41','Nutritional marasmus','Endocrine','E40-E46','IV',true,true),
('E43','Unspecified severe protein-energy malnutrition','Endocrine','E40-E46','IV',true,true),
('E44.0','Moderate protein-energy malnutrition','Endocrine','E40-E46','IV',true,true),
('E46','Unspecified protein-energy malnutrition','Endocrine','E40-E46','IV',true,true),
('E50.9','Vitamin A deficiency, unspecified','Endocrine','E50-E64','IV',true,true),
('E55.9','Vitamin D deficiency, unspecified','Endocrine','E50-E64','IV',true,true),
('E10.5','Type 1 DM with peripheral circulatory complications','Endocrine','E10-E14','IV',true,true),
('E11.5','Type 2 DM with peripheral circulatory complications','Endocrine','E10-E14','IV',true,true),
('E83.5','Disorders of calcium metabolism','Endocrine','E70-E90','IV',true,true),
('E87.1','Hyponatraemia','Endocrine','E70-E90','IV',true,true),
('E87.6','Hypokalaemia','Endocrine','E70-E90','IV',true,true),
('E87.7','Fluid overload','Endocrine','E70-E90','IV',true,true),
('F10.2','Alcohol dependence syndrome','Mental','F10-F19','V',true,true),
('F20.9','Schizophrenia, unspecified','Mental','F20-F29','V',true,true),
('F32.9','Depressive episode, unspecified','Mental','F30-F39','V',true,true),
('F41.1','Generalised anxiety disorder','Mental','F40-F48','V',true,true),
('G03.9','Meningitis, unspecified','Nervous System','G00-G09','VI',true,true),
('G04.9','Encephalitis, unspecified','Nervous System','G00-G09','VI',true,true),
('G20','Parkinson disease','Nervous System','G20-G26','VI',true,true),
('G35','Multiple sclerosis','Nervous System','G35-G37','VI',true,true),
('G40.9','Epilepsy, unspecified','Nervous System','G40-G47','VI',true,true),
('G43.9','Migraine, unspecified','Nervous System','G43-G44','VI',true,true),
('G45.9','Transient cerebral ischaemic attack, unspecified','Nervous System','G45-G46','VI',true,true),
('G62.9','Polyneuropathy, unspecified','Nervous System','G60-G64','VI',true,true),
('H25.9','Senile cataract, unspecified','Eye','H25-H28','VII',true,true),
('H26.9','Cataract, unspecified','Eye','H25-H28','VII',true,true),
('H36.0','Diabetic retinopathy','Eye','H30-H36','VII',true,true),
('H40.9','Glaucoma, unspecified','Eye','H40-H42','VII',true,true),
('I10','Essential (primary) hypertension','Cardiovascular','I10-I15','IX',true,true),
('I11.9','Hypertensive heart disease without heart failure','Cardiovascular','I10-I15','IX',true,true),
('I12.9','Hypertensive renal disease without renal failure','Cardiovascular','I10-I15','IX',true,true),
('I13.9','Hypertensive heart and renal disease, unspecified','Cardiovascular','I10-I15','IX',true,true),
('I20.0','Unstable angina','Cardiovascular','I20-I25','IX',true,true),
('I20.9','Angina pectoris, unspecified','Cardiovascular','I20-I25','IX',true,true),
('I21.0','Acute transmural MI of anterior wall','Cardiovascular','I20-I25','IX',true,true),
('I21.1','Acute transmural MI of inferior wall','Cardiovascular','I20-I25','IX',true,true),
('I21.4','Acute subendocardial MI','Cardiovascular','I20-I25','IX',true,true),
('I21.9','Acute MI, unspecified','Cardiovascular','I20-I25','IX',true,true),
('I22.9','Subsequent MI, unspecified','Cardiovascular','I20-I25','IX',true,true),
('I25.1','Atherosclerotic heart disease of native coronary artery','Cardiovascular','I20-I25','IX',true,true),
('I25.9','Chronic ischaemic heart disease, unspecified','Cardiovascular','I20-I25','IX',true,true),
('I50.0','Congestive heart failure','Cardiovascular','I50-I52','IX',true,true),
('I50.1','Left ventricular failure','Cardiovascular','I50-I52','IX',true,true),
('I50.9','Heart failure, unspecified','Cardiovascular','I50-I52','IX',true,true),
('I61.9','Intracerebral haemorrhage, unspecified','Cardiovascular','I60-I69','IX',true,true),
('I63.9','Cerebral infarction, unspecified','Cardiovascular','I60-I69','IX',true,true),
('I64','Stroke, not specified as haemorrhage or infarction','Cardiovascular','I60-I69','IX',true,true),
('I47.2','Ventricular tachycardia','Cardiovascular','I44-I49','IX',true,true),
('I48.0','Paroxysmal atrial fibrillation','Cardiovascular','I44-I49','IX',true,true),
('I48.9','Atrial fibrillation and flutter, unspecified','Cardiovascular','I44-I49','IX',true,true),
('I49.9','Cardiac arrhythmia, unspecified','Cardiovascular','I44-I49','IX',true,true),
('I05.9','Mitral valve disease, unspecified','Cardiovascular','I05-I09','IX',true,true),
('I08.0','Disorders of both mitral and aortic valves','Cardiovascular','I05-I09','IX',true,true),
('I26.9','Pulmonary embolism without mention of acute cor pulmonale','Cardiovascular','I26-I28','IX',true,true),
('I27.9','Pulmonary heart disease, unspecified','Cardiovascular','I26-I28','IX',true,true),
('I70.2','Atherosclerosis of arteries of extremities','Cardiovascular','I70-I79','IX',true,true),
('I83.9','Varicose veins of lower extremities without ulcer/inflammation','Cardiovascular','I80-I89','IX',true,true),
('J00','Acute nasopharyngitis (common cold)','Respiratory','J00-J06','X',true,true),
('J02.9','Acute pharyngitis, unspecified','Respiratory','J00-J06','X',true,true),
('J03.9','Acute tonsillitis, unspecified','Respiratory','J00-J06','X',true,true),
('J06.9','Acute upper respiratory infection, unspecified','Respiratory','J00-J06','X',true,true),
('J18.0','Bronchopneumonia, unspecified','Respiratory','J09-J18','X',true,true),
('J18.1','Lobar pneumonia, unspecified','Respiratory','J09-J18','X',true,true),
('J18.9','Pneumonia, unspecified organism','Respiratory','J09-J18','X',true,true),
('J45.0','Predominantly allergic asthma','Respiratory','J40-J47','X',true,true),
('J45.1','Nonallergic asthma','Respiratory','J40-J47','X',true,true),
('J45.9','Asthma, unspecified','Respiratory','J40-J47','X',true,true),
('J46','Status asthmaticus','Respiratory','J40-J47','X',true,true),
('J44.0','COPD with acute lower respiratory infection','Respiratory','J40-J47','X',true,true),
('J44.1','COPD with acute exacerbation','Respiratory','J40-J47','X',true,true),
('J44.9','COPD, unspecified','Respiratory','J40-J47','X',true,true),
('J90','Pleural effusion not elsewhere classified','Respiratory','J86-J94','X',true,true),
('J93.9','Pneumothorax, unspecified','Respiratory','J86-J94','X',true,true),
('K25.9','Gastric ulcer, unspecified','Digestive','K25-K27','XI',true,true),
('K26.9','Duodenal ulcer, unspecified','Digestive','K25-K27','XI',true,true),
('K27.9','Peptic ulcer, unspecified','Digestive','K25-K27','XI',true,true),
('K29.5','Chronic gastritis, unspecified','Digestive','K29-K31','XI',true,true),
('K35.8','Acute appendicitis with other complications','Digestive','K35-K38','XI',true,true),
('K37','Unspecified appendicitis','Digestive','K35-K38','XI',true,true),
('K40.9','Unilateral inguinal hernia, without obstruction or gangrene','Digestive','K40-K46','XI',true,true),
('K41.9','Unilateral femoral hernia, without obstruction or gangrene','Digestive','K40-K46','XI',true,true),
('K43.9','Ventral hernia without obstruction or gangrene','Digestive','K40-K46','XI',true,true),
('K57.3','Diverticular disease of large intestine without perforation','Digestive','K55-K63','XI',true,true),
('K59.0','Constipation, unspecified','Digestive','K55-K63','XI',true,true),
('K70.3','Alcoholic cirrhosis of liver','Digestive','K70-K77','XI',true,true),
('K72.9','Hepatic failure, unspecified','Digestive','K70-K77','XI',true,true),
('K74.6','Other and unspecified cirrhosis of liver','Digestive','K70-K77','XI',true,true),
('K80.1','Calculus of gallbladder with other cholecystitis','Digestive','K80-K87','XI',true,true),
('K80.2','Calculus of gallbladder without cholecystitis','Digestive','K80-K87','XI',true,true),
('K80.5','Calculus of bile duct without cholangitis/cholecystitis','Digestive','K80-K87','XI',true,true),
('K85.9','Acute pancreatitis, unspecified','Digestive','K80-K87','XI',true,true),
('K86.1','Other chronic pancreatitis','Digestive','K80-K87','XI',true,true),
('K92.1','Melaena','Digestive','K90-K93','XI',true,true),
('K92.2','Gastrointestinal haemorrhage, unspecified','Digestive','K90-K93','XI',true,true),
('L01.0','Impetigo (any organism)','Skin','L00-L08','XII',true,true),
('L02.9','Cutaneous abscess, furuncle and carbuncle, unspecified','Skin','L00-L08','XII',true,true),
('L03.9','Cellulitis, unspecified','Skin','L00-L08','XII',true,true),
('L20.9','Atopic dermatitis, unspecified','Skin','L20-L30','XII',true,true),
('L29.9','Pruritus, unspecified','Skin','L20-L30','XII',true,true),
('M05.9','Seropositive rheumatoid arthritis, unspecified','Musculoskeletal','M05-M14','XIII',true,true),
('M06.9','Rheumatoid arthritis, unspecified','Musculoskeletal','M05-M14','XIII',true,true),
('M10.9','Gout, unspecified','Musculoskeletal','M05-M14','XIII',true,true),
('M17.9','Gonarthrosis, unspecified','Musculoskeletal','M15-M19','XIII',true,true),
('M19.9','Arthrosis, unspecified','Musculoskeletal','M15-M19','XIII',true,true),
('M47.9','Spondylosis, unspecified','Musculoskeletal','M45-M49','XIII',true,true),
('M54.5','Low back pain','Musculoskeletal','M54-M54','XIII',true,true),
('M79.3','Panniculitis','Musculoskeletal','M79-M79','XIII',true,true),
('N00.9','Acute nephritic syndrome with unspecified morphological changes','Genitourinary','N00-N08','XIV',true,true),
('N03.9','Chronic nephritic syndrome, unspecified','Genitourinary','N00-N08','XIV',true,true),
('N04.9','Nephrotic syndrome, unspecified','Genitourinary','N00-N08','XIV',true,true),
('N17.9','Acute kidney failure, unspecified','Genitourinary','N17-N19','XIV',true,true),
('N18.4','Chronic kidney disease, stage 4','Genitourinary','N17-N19','XIV',true,true),
('N18.5','Chronic kidney disease, stage 5','Genitourinary','N17-N19','XIV',true,true),
('N18.9','Chronic kidney disease, unspecified','Genitourinary','N17-N19','XIV',true,true),
('N20.0','Calculus of kidney','Genitourinary','N20-N23','XIV',true,true),
('N20.1','Calculus of ureter','Genitourinary','N20-N23','XIV',true,true),
('N20.9','Urinary calculus, unspecified','Genitourinary','N20-N23','XIV',true,true),
('N23','Unspecified renal colic','Genitourinary','N20-N23','XIV',true,true),
('N30.0','Acute cystitis','Genitourinary','N30-N39','XIV',true,true),
('N39.0','Urinary tract infection, site not specified','Genitourinary','N30-N39','XIV',true,true),
('N40','Hyperplasia of prostate','Genitourinary','N40-N51','XIV',true,true),
('N70.9','Salpingitis and oophoritis, unspecified','Genitourinary','N70-N77','XIV',true,true),
('N80.0','Endometriosis of uterus','Genitourinary','N80-N98','XIV',true,true),
('N83.2','Other and unspecified ovarian cysts','Genitourinary','N80-N98','XIV',true,true),
('O03.9','Spontaneous abortion, complete/unspecified, without complication','Obstetrics','O00-O08','XV',true,true),
('O10.0','Pre-existing essential hypertension complicating pregnancy','Obstetrics','O10-O16','XV',true,true),
('O11','Pre-existing hypertensive disorder with superimposed proteinuria','Obstetrics','O10-O16','XV',true,true),
('O14.1','Severe pre-eclampsia','Obstetrics','O10-O16','XV',true,true),
('O14.9','Pre-eclampsia, unspecified','Obstetrics','O10-O16','XV',true,true),
('O15.0','Eclampsia in pregnancy','Obstetrics','O10-O16','XV',true,true),
('O20.0','Threatened abortion','Obstetrics','O20-O29','XV',true,true),
('O24.4','Diabetes mellitus arising in pregnancy','Obstetrics','O20-O29','XV',true,true),
('O36.3','Maternal care for signs of foetal hypoxia','Obstetrics','O30-O48','XV',true,true),
('O42.0','Premature rupture of membranes, onset of labour within 24hrs','Obstetrics','O40-O48','XV',true,true),
('O42.1','PROM, onset of labour after 24 hours','Obstetrics','O40-O48','XV',true,true),
('O60.1','Preterm labour with preterm delivery','Obstetrics','O60-O75','XV',true,true),
('O62.2','Other uterine inertia','Obstetrics','O60-O75','XV',true,true),
('O63.9','Long labour, unspecified','Obstetrics','O60-O75','XV',true,true),
('O64.0','Obstructed labour due to incomplete rotation of foetal head','Obstetrics','O60-O75','XV',true,true),
('O67.9','Intrapartum haemorrhage, unspecified','Obstetrics','O60-O75','XV',true,true),
('O72.0','Third-stage haemorrhage','Obstetrics','O60-O75','XV',true,true),
('O72.1','Other immediate postpartum haemorrhage','Obstetrics','O60-O75','XV',true,true),
('O80','Single spontaneous delivery','Obstetrics','O80-O84','XV',true,true),
('O82.0','Delivery by elective caesarean section','Obstetrics','O80-O84','XV',true,true),
('O82.1','Delivery by emergency caesarean section','Obstetrics','O80-O84','XV',true,true),
('O82.9','Delivery by caesarean section, unspecified','Obstetrics','O80-O84','XV',true,true),
('O85','Puerperal sepsis','Obstetrics','O85-O92','XV',true,true),
('O90.3','Peripartum cardiomyopathy','Obstetrics','O85-O92','XV',true,true),
('P05.1','Small for gestational age','Perinatal','P05-P08','XVI',true,true),
('P07.1','Other low birth weight','Perinatal','P05-P08','XVI',true,true),
('P07.3','Other preterm infants','Perinatal','P05-P08','XVI',true,true),
('P21.0','Severe birth asphyxia','Perinatal','P20-P29','XVI',true,true),
('P21.9','Birth asphyxia, unspecified','Perinatal','P20-P29','XVI',true,true),
('P22.0','Respiratory distress syndrome of newborn','Perinatal','P20-P29','XVI',true,true),
('P36.9','Bacterial sepsis of newborn, unspecified','Perinatal','P35-P39','XVI',true,true),
('P55.0','Rh isoimmunisation of newborn','Perinatal','P50-P61','XVI',true,true),
('P59.0','Neonatal jaundice associated with preterm delivery','Perinatal','P50-P61','XVI',true,true),
('P59.9','Neonatal jaundice, unspecified','Perinatal','P50-P61','XVI',true,true),
('Q21.1','Atrial septal defect','Congenital','Q20-Q28','XVII',true,true),
('Q21.0','Ventricular septal defect','Congenital','Q20-Q28','XVII',true,true),
('Q35.9','Cleft palate, unspecified','Congenital','Q35-Q37','XVII',true,true),
('Q53.9','Undescended testicle, unspecified','Congenital','Q50-Q56','XVII',true,true),
('R00.0','Tachycardia, unspecified','Symptoms','R00-R09','XVIII',true,true),
('R04.2','Haemoptysis','Symptoms','R00-R09','XVIII',true,true),
('R05','Cough','Symptoms','R00-R09','XVIII',true,true),
('R06.0','Dyspnoea','Symptoms','R00-R09','XVIII',true,true),
('R06.2','Wheezing','Symptoms','R00-R09','XVIII',true,true),
('R07.4','Chest pain, unspecified','Symptoms','R07-R07','XVIII',true,true),
('R10.4','Other and unspecified abdominal pain','Symptoms','R10-R19','XVIII',true,true),
('R11','Nausea and vomiting','Symptoms','R10-R19','XVIII',true,true),
('R17','Unspecified jaundice','Symptoms','R10-R19','XVIII',true,true),
('R18','Ascites','Symptoms','R10-R19','XVIII',true,true),
('R21','Rash and other nonspecific skin eruption','Symptoms','R20-R23','XVIII',true,true),
('R50.9','Fever, unspecified','Symptoms','R50-R69','XVIII',true,true),
('R51','Headache','Symptoms','R50-R69','XVIII',true,true),
('R55','Syncope and collapse','Symptoms','R50-R69','XVIII',true,true),
('R57.0','Cardiogenic shock','Symptoms','R50-R69','XVIII',true,true),
('R57.9','Shock, unspecified','Symptoms','R50-R69','XVIII',true,true),
('R73.0','Abnormal glucose tolerance test','Symptoms','R70-R79','XVIII',true,true),
('S06.0','Concussion','Injury','S00-S09','XIX',true,true),
('S06.3','Focal brain injury','Injury','S00-S09','XIX',true,true),
('S22.0','Fracture of thoracic vertebra','Injury','S20-S29','XIX',true,true),
('S32.0','Fracture of lumbar vertebra','Injury','S30-S39','XIX',true,true),
('S42.2','Fracture of upper end of humerus','Injury','S40-S49','XIX',true,true),
('S52.5','Fracture of lower end of radius','Injury','S50-S59','XIX',true,true),
('S72.0','Fracture of neck of femur','Injury','S70-S79','XIX',true,true),
('S72.1','Pertrochanteric fracture','Injury','S70-S79','XIX',true,true),
('S82.0','Fracture of patella','Injury','S80-S89','XIX',true,true),
('S82.1','Fracture of upper end of tibia','Injury','S80-S89','XIX',true,true),
('T14.0','Superficial injury of unspecified body region','Injury','T08-T14','XIX',true,true),
('T14.1','Open wound of unspecified body region','Injury','T08-T14','XIX',true,true),
('T30.0','Burn of unspecified body region, unspecified degree','Injury','T20-T32','XIX',true,true),
('T39.0','Poisoning: salicylates','Injury','T36-T50','XIX',true,true),
('T40.0','Poisoning: opium','Injury','T36-T50','XIX',true,true),
('T42.4','Poisoning: benzodiazepines','Injury','T36-T50','XIX',true,true),
('T65.9','Toxic effects of unspecified substance','Injury','T51-T65','XIX',true,true),
('V89.9','Motor vehicle accident, unspecified','External Causes','V80-V89','XX',true,true),
('W19','Unspecified fall','External Causes','W00-W19','XX',true,true),
('X70','Intentional self-harm by hanging','External Causes','X60-X84','XX',true,true),
('X84','Intentional self-harm by unspecified means','External Causes','X60-X84','XX',true,true),
('Y83.9','Surgical procedure as cause of abnormal reaction','External Causes','Y83-Y84','XX',true,true),
('Z03.9','Observation for suspected disease, ruled out, unspecified','Z-Codes','Z00-Z13','XXI',true,true),
('Z11.1','Screening for respiratory tuberculosis','Z-Codes','Z00-Z13','XXI',true,false),
('Z22.1','Carrier of typhoid fever','Z-Codes','Z20-Z29','XXI',true,true),
('Z34.0','Supervision of normal first pregnancy','Z-Codes','Z30-Z39','XXI',true,true),
('Z34.9','Supervision of normal pregnancy, unspecified','Z-Codes','Z30-Z39','XXI',true,true),
('Z38.0','Singleton, born in hospital','Z-Codes','Z30-Z39','XXI',true,true),
('Z51.1','Chemotherapy session for neoplasm','Z-Codes','Z40-Z54','XXI',true,true),
('Z51.5','Palliative care','Z-Codes','Z40-Z54','XXI',true,true),
('Z79.4','Long-term (current) use of insulin','Z-Codes','Z70-Z99','XXI',true,true),
('Z87.1','Personal history of infectious and parasitic diseases','Z-Codes','Z80-Z99','XXI',true,false),
('Z94.0','Kidney transplant status','Z-Codes','Z80-Z99','XXI',true,true),
('Z96.6','Presence of orthopaedic joint implants','Z-Codes','Z80-Z99','XXI',true,true);

-- Seed system default code set per hospital
INSERT INTO icd10_code_sets (hospital_id, set_name, set_type, version, description, total_codes, is_active)
SELECT h.id, 'India Modified ICD-10 (HMS Default)', 'system_default', 'ICD-10 India 2022',
  'Pre-loaded with 500 most common diagnoses in Indian Tier 2/3 hospitals.', 500, true
FROM hospitals h
WHERE NOT EXISTS (SELECT 1 FROM icd10_code_sets cs WHERE cs.hospital_id = h.id AND cs.set_type = 'system_default');

-- Seed hospital ICD settings
INSERT INTO hospital_icd_settings (hospital_id, active_set, show_common_first)
SELECT h.id, 'all', true
FROM hospitals h
WHERE NOT EXISTS (SELECT 1 FROM hospital_icd_settings his WHERE his.hospital_id = h.id);
